---
# See https://github.com/ansible/ansible-examples/blob/master/language_features/register_logic.yml

- name: "{{ item.name }} / editable"
  set_fact: pkg="{{ item }}"

- name: "{{ pkg.name }} / editable check"
  shell: "{{ VENV_PATH }}/bin/pip list -e | grep \"^{{ pkg.name }} \""
  ignore_errors: yes
  register: editable_result

- name: "{{ pkg.name }} / install as editable"
  shell: "{{ VENV_PATH }}/bin/pip install -e {{ pkg.path }}"
  args:
    chdir: "{{ pkg.parent }}"
  when: editable_result.rc == 1
