---

- name: "Install UbuntuGIS PPA"
  become: yes
  become_user: root
  apt_repository: repo="ppa:{{ item }}"
  with_items:
    - "ubuntugis/ubuntugis-unstable"

- name: Install PostgreSQL
  become: yes
  become_user: root
  apt: name=postgresql-9.3-postgis-2.1 state=present

# psycopg2 is necessary for postgresql_db tasks
- name: Install Psycopg2
  become: yes
  become_user: root
  apt: name={{ item }} state=present
  with_items:
    - python-psycopg2

- name: Create PostGIS Template Database
  become: yes
  become_user: postgres
  postgresql_db:
    name: template_postgis
    encoding: 'UTF8'
    template: 'template1'

- name: Create PostGIS Extension
  become: yes
  become_user: postgres
  postgresql_ext:
    name: postgis
    db: template_postgis

- name: Create PostGIS Topology Extension
  become: yes
  become_user: postgres
  postgresql_ext:
    name: postgis_topology
    db: template_postgis

- name: Create fuzzystrmatch Extension
  become: yes
  become_user: postgres
  postgresql_ext:
    name: fuzzystrmatch
    db: template_postgis
